# Generated by Django 4.1.4 on 2022-12-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'IndustryType',
                'verbose_name_plural': 'IndustryTypes',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('industry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_type_company', to='myapp.industrytype')),
            ],
            options={
                'verbose_name': 'IndustryType',
                'verbose_name_plural': 'IndustryTypes',
            },
        ),
    ]
