# Generated by Django 4.0.3 on 2022-12-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
